// <auto-generated />
using System;
using GraphAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphAPI.Migrations
{
    [DbContext(typeof(GraphDbContext))]
    [Migration("20190430121749_iit")]
    partial class iit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphAPI.Models.ConfigurationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(1000);

                    b.Property<long>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("ConfigurationType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("853bf959-2fab-4b6b-9390-98a53c8e210f"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "HeightThreshold",
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("8c8132ce-b561-4925-96bb-15a32c5dcdcd"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "StaggerThreshold",
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("4912c143-c04e-4d70-8f7c-c95bb279fdcf"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "ArcThreshold",
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("63229215-56a9-48eb-b5be-72edb90d7a53"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "ArcingIntensityThreshold",
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("a77d6b66-0a44-497e-bcf4-7ca57f105499"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "SustainedStaggerDistanceThreshold",
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("d3666b8d-a0cd-4db0-86a1-a76df3f871f7"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "SustainedArcingIntensityThreshold",
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("b015c95f-f687-455c-9f12-99e6a43362e0"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "SustainedArcingNumberOfArcsThreshold",
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("db7b21a5-6e92-45e9-b92b-493df455fc2c"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Name = "SustainedArcingDistanceThreshold",
                            UpdatedAt = 9223372036854775807L
                        });
                });

            modelBuilder.Entity("GraphAPI.Models.GlobalConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ConfigTypeId");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<float?>("Max");

                    b.Property<float?>("Min");

                    b.Property<long>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("ConfigTypeId");

                    b.HasIndex("Max")
                        .HasName("INDEX_MAX");

                    b.HasIndex("Min")
                        .HasName("INDEX_MIN");

                    b.ToTable("GlobalConfiguration");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bac22e3-1d3c-45d5-b03a-738b734457a2"),
                            ConfigTypeId = new Guid("853bf959-2fab-4b6b-9390-98a53c8e210f"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 3.4f,
                            Min = 2.3f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("cb3897b5-625f-46be-b44b-1c1b8a70a527"),
                            ConfigTypeId = new Guid("8c8132ce-b561-4925-96bb-15a32c5dcdcd"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 3.43f,
                            Min = 2.35f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("23d98649-6626-40de-9685-1b1f7c37084a"),
                            ConfigTypeId = new Guid("4912c143-c04e-4d70-8f7c-c95bb279fdcf"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 4.4f,
                            Min = 3.3f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("4aa8fd18-80fb-4228-b8dd-409e7aa387c9"),
                            ConfigTypeId = new Guid("63229215-56a9-48eb-b5be-72edb90d7a53"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 4.45f,
                            Min = 3.35f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("a0c626ca-72a2-4aa4-b721-4933aa9e3d8e"),
                            ConfigTypeId = new Guid("a77d6b66-0a44-497e-bcf4-7ca57f105499"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 5.45f,
                            Min = 4.35f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("d353e98d-f8e2-4d0a-b823-a683d74a99bd"),
                            ConfigTypeId = new Guid("d3666b8d-a0cd-4db0-86a1-a76df3f871f7"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 4.44f,
                            Min = 3.37f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("52bc54d0-c766-441f-9b88-f1d9dfc6e293"),
                            ConfigTypeId = new Guid("b015c95f-f687-455c-9f12-99e6a43362e0"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 4.41f,
                            Min = 3.33f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("6f7b3f57-0530-497a-8094-650453f1354b"),
                            ConfigTypeId = new Guid("db7b21a5-6e92-45e9-b92b-493df455fc2c"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 4.48f,
                            Min = 3.32f,
                            UpdatedAt = 9223372036854775807L
                        });
                });

            modelBuilder.Entity("GraphAPI.Models.Mast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Lon")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("Lat")
                        .HasName("INDEX_LAT");

                    b.HasIndex("Lon")
                        .HasName("INDEX_LON");

                    b.ToTable("Mast");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6705669e-00fd-4f56-8138-0421b75f4f56"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Lat = 16.069968m,
                            Lon = 108.232043m,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("d35b4e13-2fdd-46b3-9898-e85036bad865"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Lat = 16.069954m,
                            Lon = 108.232043m,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("fc9bb638-95a1-48f6-bc9c-ebbb17db90d7"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Lat = 16.069968m,
                            Lon = 108.232023m,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            Id = new Guid("498f054e-65c8-4cd0-8c8e-07d5a3e5d6fa"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Lat = 16.069971m,
                            Lon = 108.232023m,
                            UpdatedAt = 9223372036854775807L
                        });
                });

            modelBuilder.Entity("GraphAPI.Models.MastConfiguration", b =>
                {
                    b.Property<Guid>("MastId");

                    b.Property<Guid>("ConfigTypeId");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<float?>("Max");

                    b.Property<float?>("Min");

                    b.Property<long>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1000);

                    b.HasKey("MastId", "ConfigTypeId");

                    b.HasAlternateKey("ConfigTypeId", "MastId");

                    b.HasIndex("Max")
                        .HasName("INDEX_MAX");

                    b.HasIndex("Min")
                        .HasName("INDEX_MIN");

                    b.ToTable("MastConfiguration");

                    b.HasData(
                        new
                        {
                            MastId = new Guid("6705669e-00fd-4f56-8138-0421b75f4f56"),
                            ConfigTypeId = new Guid("853bf959-2fab-4b6b-9390-98a53c8e210f"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            Max = 3.35f,
                            Min = 2.35f,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            MastId = new Guid("d35b4e13-2fdd-46b3-9898-e85036bad865"),
                            ConfigTypeId = new Guid("853bf959-2fab-4b6b-9390-98a53c8e210f"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            UpdatedAt = 9223372036854775807L
                        },
                        new
                        {
                            MastId = new Guid("d35b4e13-2fdd-46b3-9898-e85036bad865"),
                            ConfigTypeId = new Guid("db7b21a5-6e92-45e9-b92b-493df455fc2c"),
                            CreatedAt = 9223372036854775807L,
                            CreatedBy = "99999999-9999-9999-9999-999999999999",
                            IsDeleted = false,
                            UpdatedAt = 9223372036854775807L
                        });
                });

            modelBuilder.Entity("GraphAPI.Models.GlobalConfiguration", b =>
                {
                    b.HasOne("GraphAPI.Models.ConfigurationType", "ConfigurationType")
                        .WithMany()
                        .HasForeignKey("ConfigTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GraphAPI.Models.MastConfiguration", b =>
                {
                    b.HasOne("GraphAPI.Models.ConfigurationType", "ConfigurationType")
                        .WithMany()
                        .HasForeignKey("ConfigTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GraphAPI.Models.Mast", "Mast")
                        .WithMany()
                        .HasForeignKey("MastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
